// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID               pgtype.UUID        `json:"id"`
	TransactionID    pgtype.UUID        `json:"transaction_id"`
	ProductID        pgtype.UUID        `json:"product_id"`
	Quantity         int64              `json:"quantity"`
	UnitPriceAmount  int64              `json:"unit_price_amount"`
	TotalPriceAmount int64              `json:"total_price_amount"`
	CurrencyCode     string             `json:"currency_code"`
	Status           string             `json:"status"`
	OrderedAt        pgtype.Timestamptz `json:"ordered_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Description  string             `json:"description"`
	PriceAmount  int64              `json:"price_amount"`
	CurrencyCode string             `json:"currency_code"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Stock struct {
	ProductID        pgtype.UUID        `json:"product_id"`
	Quantity         int64              `json:"quantity"`
	ReservedQuantity int64              `json:"reserved_quantity"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Transaction struct {
	ID               pgtype.UUID        `json:"id"`
	TotalPriceAmount int64              `json:"total_price_amount"`
	CurrencyCode     string             `json:"currency_code"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
