// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    transaction_id,
    product_id,
    quantity,
    unit_price_amount,
    total_price_amount,
    currency_code,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, transaction_id, product_id, quantity, unit_price_amount, total_price_amount, currency_code, status, ordered_at, updated_at
`

type CreateOrderParams struct {
	TransactionID    pgtype.UUID `json:"transaction_id"`
	ProductID        pgtype.UUID `json:"product_id"`
	Quantity         int32       `json:"quantity"`
	UnitPriceAmount  int32       `json:"unit_price_amount"`
	TotalPriceAmount int32       `json:"total_price_amount"`
	CurrencyCode     string      `json:"currency_code"`
	Status           string      `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.TransactionID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPriceAmount,
		arg.TotalPriceAmount,
		arg.CurrencyCode,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPriceAmount,
		&i.TotalPriceAmount,
		&i.CurrencyCode,
		&i.Status,
		&i.OrderedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, transaction_id, product_id, quantity, unit_price_amount, total_price_amount, currency_code, status, ordered_at, updated_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPriceAmount,
		&i.TotalPriceAmount,
		&i.CurrencyCode,
		&i.Status,
		&i.OrderedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrdersByStatus = `-- name: ListOrdersByStatus :many
SELECT id, transaction_id, product_id, quantity, unit_price_amount, total_price_amount, currency_code, status, ordered_at, updated_at
FROM orders
WHERE status = $1
ORDER BY ordered_at DESC
LIMIT $3
OFFSET $2
`

type ListOrdersByStatusParams struct {
	Status      string `json:"status"`
	OffsetCount int32  `json:"offset_count"`
	LimitCount  int32  `json:"limit_count"`
}

func (q *Queries) ListOrdersByStatus(ctx context.Context, arg ListOrdersByStatusParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByStatus, arg.Status, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPriceAmount,
			&i.TotalPriceAmount,
			&i.CurrencyCode,
			&i.Status,
			&i.OrderedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByTransactionID = `-- name: ListOrdersByTransactionID :many
SELECT id, transaction_id, product_id, quantity, unit_price_amount, total_price_amount, currency_code, status, ordered_at, updated_at
FROM orders
WHERE transaction_id = $1
ORDER BY ordered_at ASC
`

func (q *Queries) ListOrdersByTransactionID(ctx context.Context, transactionID pgtype.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByTransactionID, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPriceAmount,
			&i.TotalPriceAmount,
			&i.CurrencyCode,
			&i.Status,
			&i.OrderedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersForProduct = `-- name: ListOrdersForProduct :many
SELECT id, transaction_id, product_id, quantity, unit_price_amount, total_price_amount, currency_code, status, ordered_at, updated_at
FROM orders
WHERE product_id = $1
ORDER BY ordered_at DESC
LIMIT $3
OFFSET $2
`

type ListOrdersForProductParams struct {
	ProductID   pgtype.UUID `json:"product_id"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

func (q *Queries) ListOrdersForProduct(ctx context.Context, arg ListOrdersForProductParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersForProduct, arg.ProductID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPriceAmount,
			&i.TotalPriceAmount,
			&i.CurrencyCode,
			&i.Status,
			&i.OrderedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET
    status = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, transaction_id, product_id, quantity, unit_price_amount, total_price_amount, currency_code, status, ordered_at, updated_at
`

type UpdateOrderStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.Status, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPriceAmount,
		&i.TotalPriceAmount,
		&i.CurrencyCode,
		&i.Status,
		&i.OrderedAt,
		&i.UpdatedAt,
	)
	return i, err
}
