// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    name,
    description,
    price_amount,
    currency_code,
    is_active
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, name, description, price_amount, currency_code, is_active, created_at, updated_at
`

type CreateProductParams struct {
	Name         string `json:"name"`
	Description  string `json:"description"`
	PriceAmount  int64  `json:"price_amount"`
	CurrencyCode string `json:"currency_code"`
	IsActive     bool   `json:"is_active"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.PriceAmount,
		arg.CurrencyCode,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceAmount,
		&i.CurrencyCode,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateProduct = `-- name: DeactivateProduct :one
UPDATE products
SET
    is_active = FALSE,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, price_amount, currency_code, is_active, created_at, updated_at
`

func (q *Queries) DeactivateProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, deactivateProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceAmount,
		&i.CurrencyCode,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, description, price_amount, currency_code, is_active, created_at, updated_at
FROM products
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceAmount,
		&i.CurrencyCode,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProducts = `-- name: ListActiveProducts :many
SELECT id, name, description, price_amount, currency_code, is_active, created_at, updated_at
FROM products
WHERE is_active = TRUE
ORDER BY created_at DESC
LIMIT $2
OFFSET $1
`

type ListActiveProductsParams struct {
	OffsetCount int32 `json:"offset_count"`
	LimitCount  int32 `json:"limit_count"`
}

func (q *Queries) ListActiveProducts(ctx context.Context, arg ListActiveProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listActiveProducts, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PriceAmount,
			&i.CurrencyCode,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
    name = $1,
    description = $2,
    price_amount = $3,
    currency_code = $4,
    is_active = $5,
    updated_at = now()
WHERE id = $6
RETURNING id, name, description, price_amount, currency_code, is_active, created_at, updated_at
`

type UpdateProductParams struct {
	Name         string      `json:"name"`
	Description  string      `json:"description"`
	PriceAmount  int64       `json:"price_amount"`
	CurrencyCode string      `json:"currency_code"`
	IsActive     bool        `json:"is_active"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Name,
		arg.Description,
		arg.PriceAmount,
		arg.CurrencyCode,
		arg.IsActive,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceAmount,
		&i.CurrencyCode,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
