// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CommitReservedStock(ctx context.Context, arg CommitReservedStockParams) (Stock, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateStock(ctx context.Context, arg CreateStockParams) (Stock, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	DeactivateProduct(ctx context.Context, id pgtype.UUID) (Product, error)
	GetOrder(ctx context.Context, id pgtype.UUID) (Order, error)
	GetProduct(ctx context.Context, id pgtype.UUID) (Product, error)
	GetStockByProductID(ctx context.Context, productID pgtype.UUID) (Stock, error)
	GetTransaction(ctx context.Context, id pgtype.UUID) (Transaction, error)
	ListActiveProducts(ctx context.Context, arg ListActiveProductsParams) ([]Product, error)
	ListLowStocks(ctx context.Context, threshold int32) ([]Stock, error)
	ListOrdersByStatus(ctx context.Context, arg ListOrdersByStatusParams) ([]Order, error)
	ListOrdersByTransactionID(ctx context.Context, transactionID pgtype.UUID) ([]Order, error)
	ListOrdersForProduct(ctx context.Context, arg ListOrdersForProductParams) ([]Order, error)
	ListTransactionsByStatus(ctx context.Context, arg ListTransactionsByStatusParams) ([]Transaction, error)
	ReleaseReservedStock(ctx context.Context, arg ReleaseReservedStockParams) (Stock, error)
	ReserveStock(ctx context.Context, arg ReserveStockParams) (Stock, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateStockQuantity(ctx context.Context, arg UpdateStockQuantityParams) (Stock, error)
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error)
	UpdateTransactionTotalPriceAmount(ctx context.Context, arg UpdateTransactionTotalPriceAmountParams) (Transaction, error)
}

var _ Querier = (*Queries)(nil)
