// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const commitReservedStock = `-- name: CommitReservedStock :one
UPDATE stocks
SET
    quantity = quantity - $1,
    reserved_quantity = reserved_quantity - $1,
    updated_at = now()
WHERE product_id = $2
  AND reserved_quantity >= $1
RETURNING product_id, quantity, reserved_quantity, created_at, updated_at
`

type CommitReservedStockParams struct {
	Quantity  int64       `json:"quantity"`
	ProductID pgtype.UUID `json:"product_id"`
}

func (q *Queries) CommitReservedStock(ctx context.Context, arg CommitReservedStockParams) (Stock, error) {
	row := q.db.QueryRow(ctx, commitReservedStock, arg.Quantity, arg.ProductID)
	var i Stock
	err := row.Scan(
		&i.ProductID,
		&i.Quantity,
		&i.ReservedQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStock = `-- name: CreateStock :one
INSERT INTO stocks (
    product_id,
    quantity
) VALUES (
    $1,
    $2
)
RETURNING product_id, quantity, reserved_quantity, created_at, updated_at
`

type CreateStockParams struct {
	ProductID pgtype.UUID `json:"product_id"`
	Quantity  int64       `json:"quantity"`
}

func (q *Queries) CreateStock(ctx context.Context, arg CreateStockParams) (Stock, error) {
	row := q.db.QueryRow(ctx, createStock, arg.ProductID, arg.Quantity)
	var i Stock
	err := row.Scan(
		&i.ProductID,
		&i.Quantity,
		&i.ReservedQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStockByProductID = `-- name: GetStockByProductID :one
SELECT product_id, quantity, reserved_quantity, created_at, updated_at
FROM stocks
WHERE product_id = $1
`

func (q *Queries) GetStockByProductID(ctx context.Context, productID pgtype.UUID) (Stock, error) {
	row := q.db.QueryRow(ctx, getStockByProductID, productID)
	var i Stock
	err := row.Scan(
		&i.ProductID,
		&i.Quantity,
		&i.ReservedQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLowStocks = `-- name: ListLowStocks :many
SELECT product_id, quantity, reserved_quantity, created_at, updated_at
FROM stocks
WHERE quantity - reserved_quantity <= $1
ORDER BY quantity - reserved_quantity ASC, updated_at DESC
`

func (q *Queries) ListLowStocks(ctx context.Context, threshold int64) ([]Stock, error) {
	rows, err := q.db.Query(ctx, listLowStocks, threshold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stock{}
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.ProductID,
			&i.Quantity,
			&i.ReservedQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseReservedStock = `-- name: ReleaseReservedStock :one
UPDATE stocks
SET
    reserved_quantity = reserved_quantity - $1,
    updated_at = now()
WHERE product_id = $2
  AND reserved_quantity >= $1
RETURNING product_id, quantity, reserved_quantity, created_at, updated_at
`

type ReleaseReservedStockParams struct {
	Quantity  int64       `json:"quantity"`
	ProductID pgtype.UUID `json:"product_id"`
}

func (q *Queries) ReleaseReservedStock(ctx context.Context, arg ReleaseReservedStockParams) (Stock, error) {
	row := q.db.QueryRow(ctx, releaseReservedStock, arg.Quantity, arg.ProductID)
	var i Stock
	err := row.Scan(
		&i.ProductID,
		&i.Quantity,
		&i.ReservedQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reserveStock = `-- name: ReserveStock :one
UPDATE stocks
SET
    reserved_quantity = reserved_quantity + $1,
    updated_at = now()
WHERE product_id = $2
  AND quantity - reserved_quantity >= $1
RETURNING product_id, quantity, reserved_quantity, created_at, updated_at
`

type ReserveStockParams struct {
	Quantity  int64       `json:"quantity"`
	ProductID pgtype.UUID `json:"product_id"`
}

func (q *Queries) ReserveStock(ctx context.Context, arg ReserveStockParams) (Stock, error) {
	row := q.db.QueryRow(ctx, reserveStock, arg.Quantity, arg.ProductID)
	var i Stock
	err := row.Scan(
		&i.ProductID,
		&i.Quantity,
		&i.ReservedQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStockQuantity = `-- name: UpdateStockQuantity :one
UPDATE stocks
SET
    quantity = $1,
    updated_at = now()
WHERE product_id = $2
RETURNING product_id, quantity, reserved_quantity, created_at, updated_at
`

type UpdateStockQuantityParams struct {
	Quantity  int64       `json:"quantity"`
	ProductID pgtype.UUID `json:"product_id"`
}

func (q *Queries) UpdateStockQuantity(ctx context.Context, arg UpdateStockQuantityParams) (Stock, error) {
	row := q.db.QueryRow(ctx, updateStockQuantity, arg.Quantity, arg.ProductID)
	var i Stock
	err := row.Scan(
		&i.ProductID,
		&i.Quantity,
		&i.ReservedQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
