// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    total_price_amount,
    currency_code,
    status
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, total_price_amount, currency_code, status, created_at, updated_at
`

type CreateTransactionParams struct {
	TotalPriceAmount int64  `json:"total_price_amount"`
	CurrencyCode     string `json:"currency_code"`
	Status           string `json:"status"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction, arg.TotalPriceAmount, arg.CurrencyCode, arg.Status)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TotalPriceAmount,
		&i.CurrencyCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, total_price_amount, currency_code, status, created_at, updated_at
FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TotalPriceAmount,
		&i.CurrencyCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactionsByStatus = `-- name: ListTransactionsByStatus :many
SELECT id, total_price_amount, currency_code, status, created_at, updated_at
FROM transactions
WHERE status = $1
ORDER BY created_at DESC
LIMIT $3
OFFSET $2
`

type ListTransactionsByStatusParams struct {
	Status      string `json:"status"`
	OffsetCount int32  `json:"offset_count"`
	LimitCount  int32  `json:"limit_count"`
}

func (q *Queries) ListTransactionsByStatus(ctx context.Context, arg ListTransactionsByStatusParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByStatus, arg.Status, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.TotalPriceAmount,
			&i.CurrencyCode,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :one
UPDATE transactions
SET
    status = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, total_price_amount, currency_code, status, created_at, updated_at
`

type UpdateTransactionStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionStatus, arg.Status, arg.ID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TotalPriceAmount,
		&i.CurrencyCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransactionTotalPriceAmount = `-- name: UpdateTransactionTotalPriceAmount :one
UPDATE transactions
SET
    total_price_amount = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, total_price_amount, currency_code, status, created_at, updated_at
`

type UpdateTransactionTotalPriceAmountParams struct {
	TotalPriceAmount int64       `json:"total_price_amount"`
	ID               pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTransactionTotalPriceAmount(ctx context.Context, arg UpdateTransactionTotalPriceAmountParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionTotalPriceAmount, arg.TotalPriceAmount, arg.ID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TotalPriceAmount,
		&i.CurrencyCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
