name: terraform-docs.yml

on:
  pull_request:
    paths:
      - ".github/workflows/terraform-docs.yml"
      - "terraform/dev/aws/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/terraform-docs.yml"
      - "terraform/dev/aws/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Check terraform docs
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: terraform/dev/aws
          config-file: .terraform-docs.yml
          output-file: README.md
          output-method: inject
          fail-on-diff: "true"
          git-push: "false"
